language: php
php: 
  - 5.3
  - 5.4
before_script:
  - composer self-update
  - composer install

script:
  - cd Magento
  - ../vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ../vendor/bin/phpcs --standard=PSR2 ./Magento/Sniffs/
  - ../vendor/bin/phpcs --standard=PSR2 ./tests/

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml

notifications:
  slack: jh:xaJ2tKSC79yf4ghtcpJugTHH