language: php
php: 
  - 5.3
  - 5.4
before_script:
  - composer self-update
  - composer install

script:
# - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./Sniffs/

after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml